#!/usr/bin/env python3
"""What, on Intel TDX, answers "the same instance"?

The review asked which claim should carry instance identity across SEV-SNP, TDX and Nitro. For
SEV-SNP we answered it with measurement: REPORT_ID, generated by the AMD-SP per guest, absent from
the SNP_LAUNCH_START inputs, and present even where CHIP_ID is masked away.

TDX is the next question and it is genuinely open. A TDREPORT carries measurements -- MRTD, the
RTMRs, MRCONFIGID, MROWNER -- and those answer "what is running", not "which instance is running
it". Two TDs booted from one image should share every one of them.

So: launch two TDX VMs from the same image, pull a TDREPORT from each, and compare every field.
Whatever differs is a candidate; if nothing differs, that is the finding, and it says a
continuity design cannot anchor on TDX the way it anchors on SEV-SNP.

Usage:  PYTHONPATH=. python3 examples/tdx_claims_run.py [--keep]
"""
import hashlib, json, os, re, subprocess, sys, time

ZONE = "us-central1-a"
PROJECT = "rats-probe"
TYPE = "c3-standard-4"

PROBE = r'''#!/bin/bash
exec > /var/log/tdx.log 2>&1
set -x
python3 - <<'PY' > /dev/console 2>>/var/log/tdx.log
import os, fcntl, ctypes, hashlib, json, socket
# struct tdx_report_req { __u8 reportdata[64]; __u8 tdreport[1024]; };
# #define TDX_CMD_GET_REPORT0 _IOWR('T', 1, struct tdx_report_req)  -> size 1088
class Req(ctypes.Structure):
    _fields_ = [("reportdata", ctypes.c_ubyte * 64), ("tdreport", ctypes.c_ubyte * 1024)]
IOC = 0xC4405401
notes = []
rep = b""
try:
    rd = hashlib.sha512(b"hatls-tdx-claims").digest()[:64]
    req = Req(); ctypes.memmove(req.reportdata, rd, 64)
    fd = os.open("/dev/tdx_guest", os.O_RDWR)
    try: fcntl.ioctl(fd, IOC, req)
    finally: os.close(fd)
    rep = bytes(req.tdreport)
    notes.append("tdreport %d bytes" % len(rep))
except Exception as e:
    notes.append("tdreport failed: %r" % (e,))
try: notes.append("kernel " + open("/proc/version").read().split()[2])
except Exception: pass
try: notes.append("tdx_guest present: %s" % os.path.exists("/dev/tdx_guest"))
except Exception: pass
out = {"host": socket.gethostname(), "tdreport": rep.hex(), "notes": notes}
payload = json.dumps(out, sort_keys=True).encode(); hx = payload.hex(); CH = 256
print("HATLSMETA %s tdx %d %s" % (out["host"], (len(hx)+CH-1)//CH, hashlib.sha256(payload).hexdigest()))
# Print the payload twice. The serial console interleaves its own lines, and a chunk damaged in
# one pass is simply taken from the other: the reader keys chunks by index, so gaps fill in.
for _pass in range(2):
    for i in range(0, len(hx), CH):
        c = hx[i:i+CH]
        print("HATLSC %04d %s" % (i//CH, c.ljust(CH, "0") if i+CH > len(hx) else c))
print("HATLSLEN %d" % len(hx))
print("HATLSEND")
PY
'''

def gcloud(*a):
    out = subprocess.run(["gcloud"] + list(a), capture_output=True, text=True, timeout=600)
    if out.returncode != 0: raise RuntimeError(f"gcloud {' '.join(a)}\n{out.stderr[:400]}")
    return out.stdout.strip()

def reassemble(txt):
    meta = re.search(r"HATLSMETA (\S+) (\S+) (\d+) ([0-9a-f]{64})", txt)
    ln = re.search(r"HATLSLEN (\d+)", txt)
    if not meta or not ln: return None
    want, digest, hexlen = int(meta.group(3)), meta.group(4), int(ln.group(1))
    chunks = {int(n): h for n, h in re.findall(r"HATLSC (\d{4}) ([0-9a-f]{256})", txt)}
    if len(chunks) != want: return None
    hx = "".join(chunks[i] for i in range(want))[:hexlen]
    try: payload = bytes.fromhex(hx)
    except ValueError: return None
    if hashlib.sha256(payload).hexdigest() != digest: return None
    return json.loads(payload)

# TDREPORT_STRUCT (1024) = REPORTMACSTRUCT(256) | TEE_TCB_INFO(239) | reserved(17) | TDINFO(512)
# REPORTMACSTRUCT = REPORTTYPE(4) RESERVED(12) CPUSVN(16) TEE_TCB_INFO_HASH(48)
#                   TEE_INFO_HASH(48) REPORTDATA(64) RESERVED(32) MAC(32)  -> MAC is at 224, not 192
FIELDS = [
    ("REPORTMACSTRUCT.reporttype", 0, 4), ("REPORTMACSTRUCT.cpusvn", 16, 16),
    ("REPORTMACSTRUCT.tcbinfohash", 32, 48), ("REPORTMACSTRUCT.teeinfohash", 80, 48),
    ("REPORTMACSTRUCT.reportdata", 128, 64), ("REPORTMACSTRUCT.mac", 224, 32),
    ("TEE_TCB_INFO", 256, 239),
    ("TDINFO.attributes", 512, 8), ("TDINFO.xfam", 520, 8),
    ("TDINFO.MRTD", 528, 48), ("TDINFO.MRCONFIGID", 576, 48),
    ("TDINFO.MROWNER", 624, 48), ("TDINFO.MROWNERCONFIG", 672, 48),
    ("TDINFO.RTMR0", 720, 48), ("TDINFO.RTMR1", 768, 48),
    ("TDINFO.RTMR2", 816, 48), ("TDINFO.RTMR3", 864, 48),
    ("TDINFO.SERVTD_HASH", 912, 48), ("TDINFO.tail", 960, 64),
]

def main():
    keep = "--keep" in sys.argv
    OUT = f"evidence/tdx-claims-{time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())}"
    os.makedirs(OUT, exist_ok=True)
    sf = os.path.join(OUT, "probe.sh"); open(sf, "w").write(PROBE)
    names = ["tdx-a", "tdx-b"]

    print(f"=== 1. LAUNCHING TWO INTEL TDX VMs FROM ONE IMAGE ({ZONE}) ===")
    for n in names:
        gcloud("compute", "instances", "create", n, f"--project={PROJECT}", f"--zone={ZONE}",
               f"--machine-type={TYPE}", "--confidential-compute-type=TDX",
               "--maintenance-policy=TERMINATE", "--image-family=ubuntu-2404-lts-amd64",
               "--image-project=ubuntu-os-cloud", f"--metadata-from-file=startup-script={sf}",
               "--quiet")
        print(f"   {n}: created")

    print("\n=== 2. WAITING FOR TDREPORTS ON THE SERIAL CONSOLE ===")
    got = {}
    deadline = time.time() + 900
    while time.time() < deadline and len(got) < len(names):
        for n in names:
            if n in got: continue
            try:
                txt = gcloud("compute", "instances", "get-serial-port-output", n,
                             f"--zone={ZONE}", f"--project={PROJECT}")
            except Exception:
                continue
            if "HATLSEND" not in txt: continue
            p = reassemble(txt)
            if p is None:
                print(f"   {n}: output present but incomplete; still waiting"); continue
            got[n] = p; print(f"   {n}: TDREPORT received and digest verified")
        if len(got) < len(names): time.sleep(20)
    json.dump(got, open(f"{OUT}/probes.json", "w"), indent=1)
    if len(got) < 2:
        print(f"   only {len(got)} of 2 reported; see {OUT}")
        if not keep: cleanup(names)
        return 1

    for n, p in got.items():
        for note in p["notes"]: print(f"   [{n}] {note}")

    print("\n=== 3. WHICH FIELDS DIFFER BETWEEN TWO TDs FROM ONE IMAGE ===")
    a, b = [bytes.fromhex(got[n]["tdreport"]) for n in names]
    same, differ = [], []
    for name, off, ln in FIELDS:
        fa, fb = a[off:off+ln], b[off:off+ln]
        (differ if fa != fb else same).append((name, fa, fb))
    for name, fa, fb in differ:
        print(f"   DIFFERS  {name:28} {fa.hex()[:24]}  vs  {fb.hex()[:24]}")
    for name, fa, _ in same:
        print(f"   same     {name:28} {fa.hex()[:24]}")

    print("\n=== 4. WHAT THIS MEANS FOR AN INSTANCE ANCHOR ===")
    cand = [n for n, _, _ in differ if not n.startswith("REPORTMACSTRUCT")]
    print(f"   fields that differ at all            : {[n for n,_,_ in differ]}")
    print(f"   candidates once the MAC is excluded  : {cand or 'NONE'}")
    if not cand:
        print("   -> a TDREPORT from one image carries nothing that separates two live TDs.")
        print("      Anchoring continuity on TDX the way SEV-SNP anchors on REPORT_ID is not")
        print("      possible from the report alone; identity must come from somewhere else.")
    json.dump({"differ": [n for n, _, _ in differ], "candidates": cand,
               "same": [n for n, _, _ in same]}, open(f"{OUT}/verdict.json", "w"), indent=1)
    print(f"\n  evidence -> {OUT}")
    if not keep: cleanup(names)
    return 0

def cleanup(names):
    print("\n=== 5. DELETING ===")
    for n in names:
        try:
            gcloud("compute", "instances", "delete", n, f"--zone={ZONE}",
                   f"--project={PROJECT}", "--quiet")
            print(f"   {n}: deleted")
        except Exception as e:
            print(f"   {n}: DELETE FAILED -- do it by hand: {e}")

if __name__ == "__main__": sys.exit(main())
